### ISSUE TITLE
Log to custom filename

### ISSUE THREAD

**Issue by SNDST00M** [webdriverio-community/wdio-geckodriver-service#11]
Add a new option to log to a specific filename like `wdio-chromedriver-service`

**Comment by christian-bromann** [comment]
@SNDST00M can you explain a bit more about your intention? Why would you like to mix driver logs?

**Comment by SNDST00M** [comment]
Each driver needs it's own log? I don't think wdio can log the nuts-and-bolts of the driver boot attempt itself

**Comment by SNDST00M** [comment]
Cross-browser testing

**Comment by christian-bromann** [comment]
> Each driver needs its own log?

Doesn't it make much easier to debug?

**Comment by SNDST00M** [comment]
Yes, and I am mixing driver logs for interop CI

**Comment by christian-bromann** [comment]
Apparently you can already do this by adding a `logFileName` option. We should document better which options are available.
