### ISSUE TITLE
Not able to use custom port

### ISSUE THREAD

**Issue by sajixavier** [webdriverio-community/wdio-geckodriver-service#31]
I am trying to add custom port to geckodriver via options. It always taking random port number.

the following line always be true and it is generating the random port number.

`this.randomPort = options.useRandomPort || config.geckoDriverRandomPort || true`

**Comment by christian-bromann** [comment]
@sajixavier how to you set the service in your config?

**Comment by christian-bromann** [comment]
I guess it should be `false` at the end. Mind raising a PR?

**Comment by sajixavier** [comment]
Sure.

**Comment by sajixavier** [comment]
https://github.com/webdriverio-community/wdio-geckodriver-service/pull/32

**Comment by christian-bromann** [comment]
Let's continue conversation there.
