### ISSUE TITLE
Wdio Geckodriver Service v5.0.0 failing to start (possibly using outdated geckodriver package)

### ISSUE THREAD

**Issue by jnhamilton8** [webdriverio-community/wdio-geckodriver-service#341]
I have installed the latest NPM packages for wdio-geckodriver-service and geckodriver as below:
`"devDependencies": {
    "@types/chai": "^4.3.5",
    "@types/supertest": "^2.0.12",
    "@wdio/allure-reporter": "^8.8.7",
    "@wdio/cli": "^8.9.0",
    "@wdio/cucumber-framework": "^8.8.7",
    "@wdio/local-runner": "^8.9.0",
    "@wdio/spec-reporter": "^8.8.7",
    "chai": "^4.3.7",
    "chromedriver": "^112.0.1",
    "dotenv": "^16.0.3",
    "geckodriver": "^4.0.0",
    "supertest": "^6.3.3",
    "ts-node": "^10.9.1",
    "wdio-chromedriver-service": "^8.1.1",
    "wdio-geckodriver-service": "^5.0.0",
    "winston": "^3.8.2"
  },`

When running the WebdriverIO tests, they fail immediately with:
`Error: Failed to initilialise launcher service unknown: Error: Couldn't initialise "wdio-geckodriver-service".
file:///Users/jane.hamilton/Repositories/webdriverioe2e/node_modules/wdio-geckodriver-service/dist/service.js:19
import { start, download } from 'geckodriver';
                ^^^^^^^^  SyntaxError: Named export 'download' not found. `

Geckodriver 4.0.0 introduced the new download export https://github.com/webdriverio-community/node-geckodriver/releases/tag/v4.0.0

However, if you expand the wdio-geckodriver-service npm package, and look in the nested geckodriver folder, it is still using geckodriver 3.2.0 and hence why I think it is failing to start.  

I think wdio-geckodriver-service v5.0.0 needs to be updated (in it's package.json) to install "geckodriver": "^4.0.0" ?

**Comment by christian-bromann** [comment]
Ouch, thanks for raising an issue. I fixed it and released a new version. Thank you!
