### ISSUE TITLE
Move project to WebdriverIO Community Org

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-geckodriver-service#5]
Hey @RafalSkorka ,

first off, thank you for creating this plugin and extending the WebdriverIO ecosystem!

We have been looking into successful WDIO plugins like this one as we want to ensure that its development can be continued even if the original maintainer decides to move on. Therefore on behalf of the WebdriverIO community I would like to ask if you would be interested to move this repository into the [WebdriverIO Community](https://github.com/webdriverio-community) organisation. It would allow us to help maintain this package, automate a few things like releases and allow others to contribute to it and make the package even better. You would of course continue to have full access to it.

What do you think? Please let me know if you have any questions.

**Comment by RafalSkorka** [comment]
sure! how to start?

**Comment by christian-bromann** [comment]
Hey Rafal,

two things are necessary,

1. move this repository into the `webdriverio-community` organisation, see more information on that in the [GitHub docs](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository)
2. then add [`wdio-user`](https://www.npmjs.com/~wdio-user) to the list of maintainer of the project on NPM

That should be it. Let me know if you have any questions. Thank you!

**Comment by RafalSkorka** [comment]
hmm. that didn't work. I got error:
> You don’t have the permission to create public repositories on webdriverio-community

**Comment by christian-bromann** [comment]
Sorry, forgot to invite you to the org first. You should be good to go now.

**Comment by RafalSkorka** [comment]
done now.

**Comment by christian-bromann** [comment]
Thank you!
